doc_type:
  SOP: "\\bSOP\\b"
  PCN: "\\bPCN\\b"
  Release Notes: "release[ _-]?notes?"
  TIP: "\\b(TIP|technical information|troubleshooting)\\b"
  Manual: "\\b(manual|instruction|guide)\\b"
  Spec: "\\b(specification|spec[- ]sheet|technical spec)\\b"
  Checklist: "\\bchecklist\\b"
  Policy: "\\b(policy|safety|compliance)\\b"
  Form: "\\bform\\b"
  Training: "\\b(training|curriculum|course)\\b"
  Drawing: "\\b(drawing|schematic|cad|wiring)\\b"

product_line:
  Gaussian: "\\b(Gaussian|S50|V40|S1|Beetle)\\b"
  Pudu: "\\b(Pudu|CC1|SH1)\\b"
  Cobotiq: "\\bCobotiq\\b"
  Third-Party: "\\b(Third[- ]Party|partner)\\b"

model:
  S50: "\\b(Scrubber\\s*50|GS50|SC50|S50)\\b"
  V40: "\\b(Vacuum\\s*40|GS40|GV40|V40)\\b"
  S1: "\\b(S1|Phantas)\\b"
  Beetle: "\\bbeetle\\b"
  CC1: "\\bCC1\\b"
  SH1: "\\bSH1\\b"
  Integration: "\\bintegration\\b"
  Ops Tools: "\\b(ops tool|operations tool)\\b"
  Data Pipeline: "\\bdata pipeline\\b"

subsystem:
  Navigation/SLAM: "\\b(slam|navigation|mapping)\\b"
  Localization: "\\blocalization\\b"
  Perception/LiDAR: "\\b(lidar|livox|perception|point cloud)\\b"
  Actuation/Brush: "\\b(brush|roller|actuator)\\b"
  Battery/Power: "\\b(battery|bms|voltage|power)\\b"
  Charging/Dock: "\\b(dock|charger|charging)\\b"
  Networking/4G: "\\b(4g|lte|network|wifi|apn|sim)\\b"
  HMI/UX: "\\b(hmi|ux|interface|screen)\\b"
  Cloud/ETL: "\\b(cloud|etl|data lake|pipeline)\\b"
  Safety: "\\bsafety\\b"
  Chassis/Mechanical: "\\b(chassis|mechanical|frame)\\b"
  Firmware: "\\b(firmware|bootloader)\\b"
