template:
  name: "Cobotiq Document Metadata"
  description: "Standard metadata for Cobotiq robotics knowledge base"
  fields:
    - label: "Doc Type"
      type: picklist
      required: true
      options_from: doc_type
    - label: "Product Line"
      type: picklist
      required: true
      options_from: product_line
    - label: "Model"
      type: picklist
      required: true
      options_from: model
    - label: "Software Version"
      type: picklist
      required: true
      options_from: software_version
    - label: "Software Version (Other)"
      type: text
      required_when: { field: "Software Version", equals: "Other" }
    - label: "Hardware Version"
      type: picklist
      required: true
      options_from: hardware_version
    - label: "Hardware Version (Other)"
      type: text
      required_when: { field: "Hardware Version", equals: "Other" }
    - label: "Subsystem"
      type: picklist
      required: true
      options_from: subsystem
    - label: "Audience"
      type: picklist
      required: true
      options_from: audience
    - label: "Priority"
      type: picklist
      required: true
      options_from: priority
      default_value: "Medium"
    - label: "Lifecycle"
      type: picklist
      required: true
      options_from: lifecycle
      default_value: "Active"
    - label: "Confidentiality"
      type: picklist
      required: true
      options_from: confidentiality
      default_value: "Internal"
    - label: "Keywords"
      type: text
      required_when: { field: "Doc Type", equals: "Other" }

classification:
  candidate_values:
    doc_type: ["SOP","PCN","Release Notes","TIP","Manual","Spec","Checklist","Policy","Form","Training","Drawing","Other",""]
    product_line: ["Gaussian","Pudu","Cobotiq","Third-Party",""]
    model: ["S50","V40","S1","Beetle","CC1","SH1","Integration","Ops Tools","Data Pipeline","N/A","Other",""]
    software_version: ["M7","M8","M9","M10","AIO 1.3","AIO 1.4","AIO 1.5","1.2","1.3","1.4","1.5","2.0","Other",""]
    hardware_version: ["Rev A","Rev B","Rev C","Mainboard v2","Sensor Pkg v1","Other",""]
    subsystem: ["Navigation/SLAM","Localization","Perception/LiDAR","Actuation/Brush","Battery/Power","Charging/Dock","Networking/4G","HMI/UX","Cloud/ETL","Safety","Chassis/Mechanical","Firmware","Other",""]
    audience: ["Operator","Technician","Engineer","Manager/Customer",""]
    priority: ["Critical","High","Medium","Low",""]
    lifecycle: ["Draft","Active","Superseded","Deprecated","Archived",""]
    confidentiality: ["Public","Internal","Restricted",""]
  llm:
    model: "gpt-4o-mini"
    temperature: 0
    max_tokens: 200
